
package com.wad.randomnumber.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandomNumber", targetNamespace = "http://service.randomnumber.wad.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RandomNumber {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUniqueNumberList", targetNamespace = "http://service.randomnumber.wad.com/", className = "com.wad.randomnumber.service.GetUniqueNumberList")
    @ResponseWrapper(localName = "getUniqueNumberListResponse", targetNamespace = "http://service.randomnumber.wad.com/", className = "com.wad.randomnumber.service.GetUniqueNumberListResponse")
    @Action(input = "http://service.randomnumber.wad.com/RandomNumber/getUniqueNumberListRequest", output = "http://service.randomnumber.wad.com/RandomNumber/getUniqueNumberListResponse")
    public List<Integer> getUniqueNumberList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRandomNumberList", targetNamespace = "http://service.randomnumber.wad.com/", className = "com.wad.randomnumber.service.GetRandomNumberList")
    @ResponseWrapper(localName = "getRandomNumberListResponse", targetNamespace = "http://service.randomnumber.wad.com/", className = "com.wad.randomnumber.service.GetRandomNumberListResponse")
    @Action(input = "http://service.randomnumber.wad.com/RandomNumber/getRandomNumberListRequest", output = "http://service.randomnumber.wad.com/RandomNumber/getRandomNumberListResponse")
    public List<Integer> getRandomNumberList(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
