
package com.wad.randomnumber.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RandomNumberService", targetNamespace = "http://service.randomnumber.wad.com/", wsdlLocation = "http://radcliffe-desk:8080/RandomNumberService/RandomNumberService?wsdl")
public class RandomNumberService
    extends Service
{

    private final static URL RANDOMNUMBERSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANDOMNUMBERSERVICE_EXCEPTION;
    private final static QName RANDOMNUMBERSERVICE_QNAME = new QName("http://service.randomnumber.wad.com/", "RandomNumberService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://radcliffe-desk:8080/RandomNumberService/RandomNumberService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANDOMNUMBERSERVICE_WSDL_LOCATION = url;
        RANDOMNUMBERSERVICE_EXCEPTION = e;
    }

    public RandomNumberService() {
        super(__getWsdlLocation(), RANDOMNUMBERSERVICE_QNAME);
    }

    public RandomNumberService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANDOMNUMBERSERVICE_QNAME, features);
    }

    public RandomNumberService(URL wsdlLocation) {
        super(wsdlLocation, RANDOMNUMBERSERVICE_QNAME);
    }

    public RandomNumberService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANDOMNUMBERSERVICE_QNAME, features);
    }

    public RandomNumberService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RandomNumberService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RandomNumber
     */
    @WebEndpoint(name = "RandomNumberPort")
    public RandomNumber getRandomNumberPort() {
        return super.getPort(new QName("http://service.randomnumber.wad.com/", "RandomNumberPort"), RandomNumber.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RandomNumber
     */
    @WebEndpoint(name = "RandomNumberPort")
    public RandomNumber getRandomNumberPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.randomnumber.wad.com/", "RandomNumberPort"), RandomNumber.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANDOMNUMBERSERVICE_EXCEPTION!= null) {
            throw RANDOMNUMBERSERVICE_EXCEPTION;
        }
        return RANDOMNUMBERSERVICE_WSDL_LOCATION;
    }

}
