//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 01:57:51 PM EDT 
//


package com.wad.jaxb.systemconfiguration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wad.jaxb.systemconfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SystemConfiguration_QNAME = new QName("", "systemConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wad.jaxb.systemconfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Keytype }
     * 
     */
    public Keytype createKeytype() {
        return new Keytype();
    }

    /**
     * Create an instance of {@link Configurationtype }
     * 
     */
    public Configurationtype createConfigurationtype() {
        return new Configurationtype();
    }

    /**
     * Create an instance of {@link Categorytype }
     * 
     */
    public Categorytype createCategorytype() {
        return new Categorytype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Configurationtype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "systemConfiguration")
    public JAXBElement<Configurationtype> createSystemConfiguration(Configurationtype value) {
        return new JAXBElement<Configurationtype>(_SystemConfiguration_QNAME, Configurationtype.class, null, value);
    }

}
