
package com.wad.systemconfiguration.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SystemConfiguration", targetNamespace = "http://service.systemconfiguration.wad.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SystemConfiguration {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBoolean", targetNamespace = "http://service.systemconfiguration.wad.com/", className = "com.wad.systemconfiguration.service.GetBoolean")
    @ResponseWrapper(localName = "getBooleanResponse", targetNamespace = "http://service.systemconfiguration.wad.com/", className = "com.wad.systemconfiguration.service.GetBooleanResponse")
    @Action(input = "http://service.systemconfiguration.wad.com/SystemConfiguration/getBooleanRequest", output = "http://service.systemconfiguration.wad.com/SystemConfiguration/getBooleanResponse")
    public boolean getBoolean(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInt", targetNamespace = "http://service.systemconfiguration.wad.com/", className = "com.wad.systemconfiguration.service.GetInt")
    @ResponseWrapper(localName = "getIntResponse", targetNamespace = "http://service.systemconfiguration.wad.com/", className = "com.wad.systemconfiguration.service.GetIntResponse")
    @Action(input = "http://service.systemconfiguration.wad.com/SystemConfiguration/getIntRequest", output = "http://service.systemconfiguration.wad.com/SystemConfiguration/getIntResponse")
    public int getInt(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getString", targetNamespace = "http://service.systemconfiguration.wad.com/", className = "com.wad.systemconfiguration.service.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://service.systemconfiguration.wad.com/", className = "com.wad.systemconfiguration.service.GetStringResponse")
    @Action(input = "http://service.systemconfiguration.wad.com/SystemConfiguration/getStringRequest", output = "http://service.systemconfiguration.wad.com/SystemConfiguration/getStringResponse")
    public String getString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
